# Generated by Django 5.2.8 on 2025-11-28 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cms', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_gallery', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='page',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='organizations.organization'),
        ),
    ]
