# Generated by Django 5.2.6 on 2025-12-06 03:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediagallery',
            options={'ordering': ['collection', 'order', '-uploaded_at'], 'verbose_name_plural': 'Media Gallery'},
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order within collection'),
        ),
        migrations.CreateModel(
            name='GalleryCollection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Event or collection name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description of the event')),
                ('event_date', models.DateField(help_text='Date of the event')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image for the collection', null=True, upload_to='gallery/collections/')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery_collections', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Gallery Collection',
                'verbose_name_plural': 'Gallery Collections',
                'ordering': ['-event_date', 'order'],
            },
        ),
        migrations.AddField(
            model_name='mediagallery',
            name='collection',
            field=models.ForeignKey(blank=True, help_text='Collection/Event this media belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='cms.gallerycollection'),
        ),
    ]
