# Generated by Django 5.0.1 on 2026-05-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productsize',
            options={'ordering': ['sort_order', 'size_name']},
        ),
        migrations.AddField(
            model_name='productsize',
            name='sort_order',
            field=models.PositiveIntegerField(default=99, help_text='Controls display order. Lower numbers appear first. Standard: XS=0, S=1, M=2, L=3, XL=4, XXL=5'),
        ),
    ]
