# Generated by Django 5.0.1 on 2026-07-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productsize_options_productsize_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
