# Generated by Django 5.2.6 on 2025-12-09 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('registration_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_teams', models.PositiveIntegerField(help_text='Maximum teams per category')),
                ('min_players_per_team', models.PositiveIntegerField(default=7)),
                ('max_players_per_team', models.PositiveIntegerField(default=15)),
                ('venue', models.CharField(max_length=300)),
                ('rules', models.TextField(blank=True)),
                ('prizes', models.TextField(blank=True)),
                ('prize_pool', models.DecimalField(blank=True, decimal_places=2, help_text='Total prize pool amount', max_digits=12, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='tournaments/banners/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open for Registration'), ('closed', 'Registration Closed'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Minimum age for this category', null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, help_text='Maximum age for this category', null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, help_text='Max teams for this category (overrides tournament default)', null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee for this category (overrides tournament default)', max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'Tournament Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='teams/logos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournamentcategory')),
            ],
            options={
                'ordering': ['-registered_at'],
                'unique_together': {('tournament', 'category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('teams', models.ManyToManyField(related_name='pools', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournament')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournamentcategory')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('tournament', 'category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1_score', models.PositiveIntegerField(blank=True, null=True)),
                ('team2_score', models.PositiveIntegerField(blank=True, null=True)),
                ('match_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=300)),
                ('round', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pool', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.pool')),
                ('team1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team')),
                ('team2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentcategory')),
            ],
            options={
                'verbose_name_plural': 'Matches',
                'ordering': ['match_date'],
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('jersey_number', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/photos/')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team')),
            ],
            options={
                'ordering': ['jersey_number'],
                'unique_together': {('team', 'jersey_number')},
            },
        ),
        migrations.CreateModel(
            name='Standing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('played', models.PositiveIntegerField(default=0)),
                ('wins', models.PositiveIntegerField(default=0)),
                ('draws', models.PositiveIntegerField(default=0)),
                ('losses', models.PositiveIntegerField(default=0)),
                ('goals_for', models.PositiveIntegerField(default=0)),
                ('goals_against', models.PositiveIntegerField(default=0)),
                ('points', models.PositiveIntegerField(default=0)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.team')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournamentcategory')),
            ],
            options={
                'ordering': ['-points', '-goals_for'],
                'unique_together': {('tournament', 'category', 'team')},
            },
        ),
    ]
