# Generated by Django 5.2.8 on 2025-11-28 20:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='captain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='captained_teams', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='standing',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='pool',
            name='teams',
            field=models.ManyToManyField(related_name='pools', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='tournaments.team'),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='team',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='standing',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='pool',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournament'),
        ),
        migrations.AddField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AlterUniqueTogether(
            name='player',
            unique_together={('team', 'jersey_number')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('tournament', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('tournament', 'name')},
        ),
    ]
