# Generated by Django 5.0.1 on 2026-07-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='accepted_rules',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='team',
            name='alt_contact_person',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='alt_contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='team',
            name='captain_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='team',
            name='mpesa_confirmation_code',
            field=models.CharField(blank=True, help_text='M-PESA Confirmation Code', max_length=50),
        ),
        migrations.AddField(
            model_name='team',
            name='mpesa_name',
            field=models.CharField(blank=True, help_text='Name registered to M-PESA', max_length=200),
        ),
    ]
