# Generated by Django 5.2.6 on 2025-11-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='prize_pool',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Total prize pool amount', max_digits=12, null=True),
        ),
    ]
