# Generated by Django 5.2.6 on 2025-12-03 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_tournament_prize_pool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='category',
            field=models.CharField(choices=[('adults', 'Adults'), ('under_15', 'Under 15'), ('under_11', 'Under 11')], max_length=20),
        ),
    ]
