# Generated by Django 5.2.6 on 2025-12-04 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
        ('tournaments', '0004_alter_tournament_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tournaments', to='organizations.organization'),
        ),
    ]
