# Generated by Django 5.2.6 on 2025-12-06 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_alter_tournament_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='organization',
        ),
    ]
