# Generated by Django 5.2.8 on 2025-12-06 04:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_remove_team_captain_remove_tournament_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='category',
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(help_text='Maximum teams per category'),
        ),
        migrations.CreateModel(
            name='TournamentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_name', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('min_age', models.PositiveIntegerField(blank=True, help_text='Minimum age for this category', null=True)),
                ('max_age', models.PositiveIntegerField(blank=True, help_text='Maximum age for this category', null=True)),
                ('max_teams', models.PositiveIntegerField(blank=True, help_text='Max teams for this category (overrides tournament default)', null=True)),
                ('registration_fee', models.DecimalField(blank=True, decimal_places=2, help_text='Fee for this category (overrides tournament default)', max_digits=10, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='tournaments.tournament')),
            ],
            options={
                'verbose_name_plural': 'Tournament Categories',
                'ordering': ['order', 'name'],
                'unique_together': {('tournament', 'name')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='match',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='tournaments.tournamentcategory'),
        ),
        migrations.AddField(
            model_name='pool',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pools', to='tournaments.tournamentcategory'),
        ),
        migrations.AddField(
            model_name='standing',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='standings', to='tournaments.tournamentcategory'),
        ),
        migrations.AddField(
            model_name='team',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='tournaments.tournamentcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='pool',
            unique_together={('tournament', 'category', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='standing',
            unique_together={('tournament', 'category', 'team')},
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together={('tournament', 'category', 'name')},
        ),
    ]
