# Generated by Django 5.2.6 on 2025-12-10 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Name of the payment link', max_length=200)),
                ('description', models.TextField(help_text='Purpose of the payment')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Fixed or minimum amount', max_digits=10)),
                ('allow_custom_amount', models.BooleanField(default=False, help_text='Allow users to enter custom amounts')),
                ('currency', models.CharField(default='KES', max_length=3)),
                ('unique_code', models.CharField(db_index=True, help_text='Unique identifier for the link', max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this payment link')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Maximum number of times this link can be used', null=True)),
                ('current_uses', models.PositiveIntegerField(default=0, help_text='Number of times this link has been used')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Expiration date for this link', null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_link',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='payments.paymentlink'),
        ),
    ]
